### ISSUE TITLE
The id variable has to be the first column in the data set

### ISSUE THREAD

**Issue by yhuang123** [graemeleehickey/joineRML#63] opened 2018-08-19 23:02 UTC
Thank for your R pjoineRML package.
For this error message: 
Error in status[length(id.col)] <- survdat2[survdat2$id == id.col[1], :  replacement has length zero

I also tested that the id variable has to be the first column in the data set

Thanks
Yangxin

**Comment by ellessenne** [comment] 2020-03-27 13:57
Duplicate of #59, let's continue the conversation there.

**Closed as completed by ellessenne** 2020-03-27 13:57 UTC
