### ISSUE TITLE
Dependency on R >= 3.6.0

### ISSUE THREAD

**Issue by ellessenne** [graemeleehickey/joineRML#65] opened 2020-03-09 10:48 UTC
Hi,
I noticed that `joineRML` now requires R >= 3.6.0. Is that really necessary?

**Comment by ellessenne** [comment] 2020-03-09 12:35
I think this might be similar to what happened with `joineR`, see this PR: petephilipson/joineR#4

**Comment by graemeleehickey** [comment] 2020-03-09 14:27
I added it because of the change in the RNG sampler used for `sample()`. To ensure that results are reproducible with a fixed seed, this seemed like the easiest solution.

See details [here](https://f.briatte.org/r/change-in-sample-function-r-3-6-0).

That said, I am happy to relax this if. Feel free to change it.

**Comment by ellessenne** [comment] 2020-03-10 08:47
I see, that makes sense!
My only concern was that R 3.6.0 is less than a year old, and that several IT departments (...) do not upgrade R often (which might leave users unable to even install `joineRML`). 
What do you think?

**Comment by graemeleehickey** [comment] 2020-07-04 13:05
Since there have not been any other comments on this and we are now on R v4.0.2, I will close this comment.

**Closed as completed by graemeleehickey** 2020-07-04 13:05 UTC
